// Code generated by "stringer -type token -linecomment tokens.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_EOF-1]
	_ = x[_Error-2]
	_ = x[_Name-3]
	_ = x[_Literal-4]
	_ = x[_Operator-5]
	_ = x[_AssignOp-6]
	_ = x[_IncOp-7]
	_ = x[_Assign-8]
	_ = x[_Define-9]
	_ = x[_Arrow-10]
	_ = x[_Star-11]
	_ = x[_Lparen-12]
	_ = x[_Lbrack-13]
	_ = x[_Lbrace-14]
	_ = x[_Rparen-15]
	_ = x[_Rbrack-16]
	_ = x[_Rbrace-17]
	_ = x[_Comma-18]
	_ = x[_Semi-19]
	_ = x[_Colon-20]
	_ = x[_Dot-21]
	_ = x[_DotDotDot-22]
	_ = x[_Break-23]
	_ = x[_Case-24]
	_ = x[_Chan-25]
	_ = x[_Const-26]
	_ = x[_Continue-27]
	_ = x[_Default-28]
	_ = x[_Defer-29]
	_ = x[_Else-30]
	_ = x[_Fallthrough-31]
	_ = x[_For-32]
	_ = x[_Func-33]
	_ = x[_Go-34]
	_ = x[_Goto-35]
	_ = x[_If-36]
	_ = x[_Import-37]
	_ = x[_Interface-38]
	_ = x[_Map-39]
	_ = x[_Package-40]
	_ = x[_Range-41]
	_ = x[_Return-42]
	_ = x[_Select-43]
	_ = x[_Struct-44]
	_ = x[_Switch-45]
	_ = x[_Type-46]
	_ = x[_Var-47]
	_ = x[tokenCount-48]
}

const _token_name = "EOFpseudo-token for reporting errorsnameliteralopop=opop=:=<-*([{)]},;:....breakcasechanconstcontinuedefaultdeferelsefallthroughforfuncgogotoifimportinterfacemappackagerangereturnselectstructswitchtypevar"

var _token_index = [...]uint8{0, 3, 36, 40, 47, 49, 52, 56, 57, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 75, 80, 84, 88, 93, 101, 108, 113, 117, 128, 131, 135, 137, 141, 143, 149, 158, 161, 168, 173, 179, 185, 191, 197, 201, 204, 204}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
